spring:
  application:
    name: ${SPRING_APPLICATION_NAME:user-management-service}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:file:/tmp/salesusers-db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful

management:
  endpoints:
    web:
      base-path: ${MANAGEMENT_ENDPOINTS_WEB_BASE_PATH:/actuator}
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:health,info}
  endpoint:
    health:
      show-details: ${MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS:never}
      probes:
        enabled: ${MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED:true}
  info:
    env:
      enabled: false
