apiVersion: v1
kind: ConfigMap
metadata:
  name: salesusers-config
  namespace: deibidsales
  labels:
    app.kubernetes.io/name: salesusers
    app.kubernetes.io/part-of: salesusers
data:
  SERVER_PORT: "8080"
  SPRING_DATASOURCE_URL: "jdbc:h2:file:/tmp/salesusers-db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE"
  SPRING_DATASOURCE_USERNAME: "sa"
  SPRING_DATASOURCE_PASSWORD: ""
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info"
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "never"
  JAVA_OPTS: "-XX:InitialRAMPercentage=25.0 -XX:MaxRAMPercentage=75.0 -XX:+UseG1GC"
