apiVersion: v1
kind: Service
metadata:
  name: salesusers-postgres
  namespace: deibidsales
  labels:
    app.kubernetes.io/name: salesusers-postgres
    app.kubernetes.io/part-of: salesusers
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: salesusers-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP
