apiVersion: v1
kind: Secret
metadata:
  name: salesusers-db-secret
  namespace: deibidsales
  labels:
    app.kubernetes.io/name: salesusers-postgres
    app.kubernetes.io/part-of: salesusers
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: salesusers
  SPRING_DATASOURCE_PASSWORD: salesuserspassword
  POSTGRES_USER: salesusers
  POSTGRES_PASSWORD: salesuserspassword
  POSTGRES_DB: salesusers
